import type { AgentProvider } from './AgentProvider';
import type { Evidence, Goal, Mission, Proposal } from '@agent-company-os/shared-types';

export interface AnthropicProviderConfig {
  apiKey?: string;
  model: string;
  betaHeader: string;
  agentId?: string;
  environmentId?: string;
}

export class AnthropicManagedAgentsProvider implements AgentProvider {
  readonly mode = 'anthropic' as const;
  constructor(private readonly config: AnthropicProviderConfig) {}

  private ensureKey() {
    if (!this.config.apiKey) {
      throw new Error('Anthropic provider is enabled but ANTHROPIC_API_KEY is missing. Set PROVIDER_MODE=mock or add API key.');
    }
  }

  private async callManagedAgent(prompt: string) {
    this.ensureKey();
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'x-api-key': this.config.apiKey!,
        'content-type': 'application/json',
        'anthropic-version': '2023-06-01',
        'anthropic-beta': this.config.betaHeader
      },
      body: JSON.stringify({
        model: this.config.model,
        max_tokens: 1000,
        metadata: { agent_id: this.config.agentId, environment_id: this.config.environmentId },
        messages: [{ role: 'user', content: prompt }]
      })
    });

    if (!response.ok) {
      const detail = await response.text();
      throw new Error(`Anthropic call failed (${response.status}): ${detail}`);
    }

    const data = await response.json() as { content?: Array<{ type: string; text?: string }> };
    const text = data.content?.find((c) => c.type === 'text')?.text;
    if (!text) throw new Error('Anthropic response missing text content');
    return text;
  }

  async generateEvidence(mission: Mission): Promise<Omit<Evidence, 'id' | 'createdAt'>> {
    const text = await this.callManagedAgent(`Generate concise evidence JSON with fields title, summary, supportingPoints, confidence for mission: ${JSON.stringify(mission)}`);
    let parsed: { title?: string; summary?: string; supportingPoints?: string[]; confidence?: number } = {};
    try { parsed = JSON.parse(text); } catch {}
    return {
      goalId: mission.goalId,
      missionId: mission.id,
      sourceType: 'anthropic',
      title: parsed.title ?? `Anthropic evidence for ${mission.title}`,
      summary: parsed.summary ?? text.slice(0, 400),
      supportingPoints: parsed.supportingPoints ?? ['Generated by Anthropic managed-agent style call'],
      confidence: parsed.confidence ?? 0.7
    };
  }

  async generateProposal(goal: Goal, evidenceBundle: Evidence[]): Promise<Omit<Proposal, 'id' | 'createdAt' | 'updatedAt' | 'status'>> {
    const text = await this.callManagedAgent(`Generate proposal JSON with fields title,problem,offer,targetCustomer,pricingHypothesis,landingCopy,outreachDraft from goal/evidence: ${JSON.stringify({ goal, evidenceBundle })}`);
    let parsed: Record<string, string> = {};
    try { parsed = JSON.parse(text); } catch {}
    return {
      goalId: goal.id,
      title: parsed.title ?? `Anthropic Proposal for ${goal.title}`,
      problem: parsed.problem ?? goal.description,
      offer: parsed.offer ?? 'Offer generated by Anthropic provider',
      targetCustomer: parsed.targetCustomer ?? 'SMB decision makers',
      pricingHypothesis: parsed.pricingHypothesis ?? '$999 pilot',
      landingCopy: parsed.landingCopy ?? text.slice(0, 500),
      outreachDraft: parsed.outreachDraft ?? 'Generated outreach draft.'
    };
  }
}
